### ISSUE TITLE
MultipleIncludedBlocks error when generating search_builder with 5.16.3

### ISSUE THREAD

**Issue by flyingzumwalt** [projectblacklight/blacklight#1337]
This prevents upgrading to the latest blacklight (5.16.3), which is a prerequisite for upgrading to blacklight 6.

```
/Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/activesupport-4.1.14/lib/active_support/concern.rb:126:in `included': Cannot define multiple 'included' blocks for a Concern (ActiveSupport::Concern::MultipleIncludedBlocks)
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/blacklight-5.16.3/app/controllers/concerns/blacklight/catalog.rb:9:in `<module:SearchContext>'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/blacklight-5.16.3/app/controllers/concerns/blacklight/catalog.rb:6:in `<module:Catalog>'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/blacklight-5.16.3/app/controllers/concerns/blacklight/catalog.rb:2:in `<top (required)>'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/activesupport-4.1.14/lib/active_support/dependencies.rb:247:in `require'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/activesupport-4.1.14/lib/active_support/dependencies.rb:247:in `block in require'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/activesupport-4.1.14/lib/active_support/dependencies.rb:230:in `block in load_dependency'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/activesupport-4.1.14/lib/active_support/dependencies.rb:633:in `new_constants_in'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/activesupport-4.1.14/lib/active_support/dependencies.rb:230:in `load_dependency'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/activesupport-4.1.14/lib/active_support/dependencies.rb:247:in `require'
	from /Users/matt/Develop/ruby/toshokan/app/controllers/catalog_controller.rb:2:in `<top (required)>'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/activesupport-4.1.14/lib/active_support/dependencies.rb:443:in `load'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/activesupport-4.1.14/lib/active_support/dependencies.rb:443:in `block in load_file'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/activesupport-4.1.14/lib/active_support/dependencies.rb:633:in `new_constants_in'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/activesupport-4.1.14/lib/active_support/dependencies.rb:442:in `load_file'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/activesupport-4.1.14/lib/active_support/dependencies.rb:342:in `require_or_load'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/activesupport-4.1.14/lib/active_support/dependencies.rb:480:in `load_missing_constant'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/activesupport-4.1.14/lib/active_support/dependencies.rb:180:in `const_missing'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/activesupport-4.1.14/lib/active_support/dependencies.rb:512:in `load_missing_constant'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/activesupport-4.1.14/lib/active_support/dependencies.rb:180:in `const_missing'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/blacklight_range_limit-5.2.0/lib/blacklight_range_limit.rb:27:in `inject!'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/blacklight_range_limit-5.2.0/lib/blacklight_range_limit/engine.rb:20:in `block in <class:Engine>'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/activesupport-4.1.14/lib/active_support/callbacks.rb:443:in `instance_exec'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/activesupport-4.1.14/lib/active_support/callbacks.rb:443:in `block in make_lambda'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/activesupport-4.1.14/lib/active_support/callbacks.rb:187:in `call'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/activesupport-4.1.14/lib/active_support/callbacks.rb:187:in `block in simple'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/activesupport-4.1.14/lib/active_support/callbacks.rb:501:in `call'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/activesupport-4.1.14/lib/active_support/callbacks.rb:501:in `block in call'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/activesupport-4.1.14/lib/active_support/callbacks.rb:501:in `each'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/activesupport-4.1.14/lib/active_support/callbacks.rb:501:in `call'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/activesupport-4.1.14/lib/active_support/callbacks.rb:86:in `run_callbacks'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/actionpack-4.1.14/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/actionpack-4.1.14/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/railties-4.1.14/lib/rails/application/finisher.rb:52:in `block in <module:Finisher>'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/railties-4.1.14/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/railties-4.1.14/lib/rails/initializable.rb:30:in `run'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/railties-4.1.14/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/matt/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
	from /Users/matt/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /Users/matt/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
	from /Users/matt/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /Users/matt/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:345:in `each'
	from /Users/matt/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:345:in `call'
	from /Users/matt/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
	from /Users/matt/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
	from /Users/matt/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/railties-4.1.14/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/railties-4.1.14/lib/rails/application.rb:300:in `initialize!'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/railties-4.1.14/lib/rails/railtie.rb:194:in `public_send'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/railties-4.1.14/lib/rails/railtie.rb:194:in `method_missing'
	from /Users/matt/Develop/ruby/toshokan/config/environment.rb:5:in `<top (required)>'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/activesupport-4.1.14/lib/active_support/dependencies.rb:247:in `require'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/activesupport-4.1.14/lib/active_support/dependencies.rb:247:in `block in require'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/activesupport-4.1.14/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/activesupport-4.1.14/lib/active_support/dependencies.rb:247:in `require'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/railties-4.1.14/lib/rails/application.rb:276:in `require_environment!'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/railties-4.1.14/lib/rails/commands/commands_tasks.rb:147:in `require_application_and_environment!'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/railties-4.1.14/lib/rails/commands/commands_tasks.rb:133:in `generate_or_destroy'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/railties-4.1.14/lib/rails/commands/commands_tasks.rb:51:in `generate'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/railties-4.1.14/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /Users/matt/.rvm/gems/ruby-2.1.4@toshokan/gems/railties-4.1.14/lib/rails/commands.rb:17:in `<top (required)>'
	from script/rails:9:in `require'
	from script/rails:9:in `<main>'
```

**Comment by flyingzumwalt** [comment]
Hack: I was able to bypass the error by commenting out all of the include blocks in blacklight-5.16.3/app/controllers/concerns/blacklight/catalog.rb while I ran the generator.

**Comment by flyingzumwalt** [comment]
As far as I can tell, this also prevents the rails server from starting when you're on blacklight 5.16.3

**Comment by jcoyne** [comment]
Do you have RAILS_ENV=production and spring in your Gemfile?

**Comment by flyingzumwalt** [comment]
spring is not in the Gemfile.  What do you mean "Do you have RAILS_ENV=production"?

**Comment by jcoyne** [comment]
I've only ever seen this problem when using spring + the production env

**Comment by jcoyne** [comment]
Have you tried removing the require here? `app/controllers/catalog_controller.rb:2`

**Comment by jcoyne** [comment]
I suspect that this module gets reopened because of that require:
https://github.com/projectblacklight/blacklight/blob/v5.16.4/app/controllers/concerns/blacklight/catalog.rb#L9

**Comment by flyingzumwalt** [comment]
That probably is the culprit.  It will take me a little time to test it.
(moved on to other stuff)

**Comment by flyingzumwalt** [comment]
That fixed it.
