### ISSUE TITLE
sort param field can't be found: pub_date_sort

### ISSUE THREAD

**Issue by domino666666** [projectblacklight/blacklight#1348]
I'm trying to run Solr without Jetty and I get an issue when I run blacklight "sort param field can't be found: pub_date_sort". Any help would be greatly appreciated?

Blacklight::Exceptions::InvalidRequest in CatalogController#index

RSolr::Error::Http - 400 Bad Request Error: {'responseHeader'=>{'status'=>400,'QTime'=>6,'params'=>{'facet'=>'true','sort'=>'score desc, pub_date_sort desc, title_sort asc','facet.query'=>['pub_date:[2010 TO *]','pub_date:[2005 TO *]','pub_date:[1990 TO *]'],'f.subject_topic_facet.facet.limit'=>'21','f.language_facet.facet.limit'=>'11','facet.field'=>['format','{!ex=pub_date_single}pub_date','subject_topic_facet','language_facet','lc_1letter_facet','subject_geo_facet','subject_era_facet'],'qt'=>'search','wt'=>'ruby','facet.pivot'=>'format,language_facet','rows'=>'10'}},'error'=>{'msg'=>'sort param field can\'t be found: pub_date_sort','code'=>400}} URI: http://127.0.0.1:8983/solr/blacklight-core/select?wt=ruby&qt=search&facet.field=format&facet.field=%7B%21ex%3Dpub_date_single%7Dpub_date&facet.field=subject_topic_facet&facet.field=language_facet&facet.field=lc_1letter_facet&facet.field=subject_geo_facet&facet.field=subject_era_facet&facet.query=pub_date%3A%5B2010+TO+*%5D&facet.query=pub_date%3A%5B2005+TO+*%5D&facet.query=pub_date%3A%5B1990+TO+*%5D&facet.pivot=format%2Clanguage_facet&&&rows=10&facet=true&f.subject_topic_facet.facet.limit=21&f.language_facet.facet.limit=11&sort=score+desc%2C+pub_date_sort+desc%2C+title_sort+asc Backtrace: C:/pgm/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rsolr-1.0.13/lib/rsolr/client.rb:284:in `adapt_response' C:/pgm/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rsolr-1.0.13/lib/rsolr/client.rb:190:in `execute' C:/pgm/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rsolr-1.0.13/lib/rsolr/client.rb:176:in `send_and_receive' C:/pgm/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/blacklight-5.17.0/lib/blacklight/solr/repository.rb:44:in `block in send_and_receive' C:/pgm/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/activesupport-4.1.14/lib/active_support/benchmarkable.rb:41:in `block in benchmark' C:/pgm/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/activesupport-4.1.14/lib/active_support/core_ext/benchmark.rb:12:in `block in ms' C:/pgm/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/benchmark.rb:294:in `realtime' C:/pgm/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/activesupport-4.1.14/lib/active_support/core_ext/benchmark.rb:12:in `ms' C:/pgm/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/activesupport-4.1.14/lib/active_support/benchmarkable.rb:41:in `benchmark' C:/pgm/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/blacklight-5.17.0/lib/blacklight/solr/repository.rb:42:in `send_and_receive' C:/pgm/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/blacklight-5.17.0/lib/blacklight/solr/repository.rb:28:in `search'

**Comment by jhriv** [comment]
Setting up via "the hard way" results in the same thing.

```
RSolr::Error::Http - 400 Bad Request Error: 'sort param field can\'t be found: pub_date_sort','code'=>400}} URI: http://127.0.0.1:8983/solr/blacklight-core/select?wt=ruby&facet.field=format&facet.field=%7B%21ex%3Dpub_date_single%7Dpub_date&facet.field=subject_topic_facet&facet.field=language_facet&facet.field=lc_1letter_facet&facet.field=subject_geo_facet&facet.field=subject_era_facet&facet.query=pub_date%3A%5B2012+TO+*%5D&facet.query=pub_date%3A%5B2007+TO+*%5D&facet.query=pub_date%3A%5B1992+TO+*%5D&facet.pivot=format%2Clanguage_facet&&&rows=10&facet=true&f.subject_topic_facet.facet.limit=21&f.language_facet.facet.limit=11&sort=score+desc%2C+pub_date_sort+desc%2C+title_sort+asc Backtrace: /var/lib/gems/2.2.0/gems/rsolr-1.1.2/lib/rsolr/client.rb:288:in `adapt_response' /var/lib/gems/2.2.0/gems/rsolr-1.1.2/lib/rsolr/client.rb:189:in `execute' /var/lib/gems/2.2.0/gems/rsolr-1.1.2/lib/rsolr/client.rb:175:in `send_and_receive' /var/lib/gems/2.2.0/gems/blacklight-6.7.3/lib/blacklight/solr/repository.rb:38:in `block in send_and_receive' /var/lib/gems/2.2.0/gems/activesupport-5.0.1/lib/active_support/benchmarkable.rb:41:in `block in benchmark' /var/lib/gems/2.2.0/gems/activesupport-5.0.1/lib/active_support/core_ext/benchmark.rb:12:in `block in ms' /usr/lib/ruby/2.2.0/benchmark.rb:303:in `realtime' /var/lib/gems/2.2.0/gems/activesupport-5.0.1/lib/active_support/core_ext/benchmark.rb:12:in `ms' /var/lib/gems/2.2.0/gems/activesupport-5.0.1/lib/active_support/benchmarkable.rb:41:in `benchmark' /var/lib/gems/2.2.0/gems/blacklight-6.7.3/lib/blacklight/solr/repository.rb:36:in `send_and_receive' /var/lib/gems/2.2.0/gems/blacklight-6.7.3/lib/blacklight/solr/repository.rb:22:in `search'
```

The test data seems to be missing any `pub_date_sort` records.

``` ruby 
      raise Blacklight::Exceptions::ECONNREFUSED, "Unable to connect to Solr instance using #{connection.inspect}: #{e.inspect}"
    rescue RSolr::Error::Http => e
      raise Blacklight::Exceptions::InvalidRequest, e.message
    end

    protected
```

**Comment by jhriv** [comment]
Further troubleshooting - the `rake solr:marc:index_test_data` creates a schema that lacks *pub_date_sort* which is clearly in `solr/conf/schema.xml` and has applicable data in `solr/sample_solr_documents.yml`. Manually adding the *pub_date_sort* field
``` bash
curl -X POST -H 'Content-type:application/json' --data-binary '{
   "add-field":{
"name":"pub_date_sort",
"type":"tint"
}
}' http://localhost:8983/solr/blacklight-core/schema
```
deleting all current data, then re-importing the data via the `rake` task shows *pub_date_sort* in the schema but there still lacks any data for *pub_date_sort*.

**grep blacklight Gemfile**
```
gem "blacklight", "~> 6.0"
gem 'blacklight-marc', '~> 6.1'
```

**gem list blacklight**
```
*** LOCAL GEMS ***

blacklight (6.7.3)
blacklight-marc (6.1.1)
``` 

Could any of this be because I am using a full Solr instance instead of solr-wrapper, and still running in *:development* environment?

**Comment by joelakes** [comment]
Hi,

Did you ever find a solution for this?

Thanks...

**Comment by jhriv** [comment]
> Did you ever find a solution for this?

I don't recall finding a solution. I am pretty certain that project got shelved, as we moved onto other things.

**Comment by barmintor** [comment]
If I read this error correctly, there are 2 possible fixes here:
1. Add the Solr field definition to the schema, update the MarcIndexer model to use `pub_date_sort` instead of `pub_date`, and reindex
2. Change the CatalogController to use `pub_date` to sort

There's a related BL7.0 issue regarding the field names, but there they are `pub_date_si` and `pub_date`, but Solr 7 appears to be more generous with the errors.

**Comment by sixtyfive** [comment]
Not sure if this is the same or a different i/Issue. I'm trying to get Blacklight to work "the easy way" to take a look at it (not sure yet if it will fit the bill). So far I've tried the following:

- `git clone https://github.com/projectblacklight/blacklight-jetty.git; cd blacklight-jetty; java -jar start.jar`
- noticed there is neither an `exampledocs` directory nor a `post.sh` file (as mentioned by [README.txt](https://github.com/projectblacklight/blacklight-jetty/blob/master/README.txt))
  - figured these might be part of Solr itself
  - downloaded `solr-8.5.2.tgz`, unpacked, looked around, didn't find `post.sh` but did find `bin/post` as well as `example/exampledocs`; after reading `bin/post -h`, tried `bin/post -c example_files example/exampledocs/*.xml`
  - found that doesn't work (`SimplePostTool: WARNING: Solr returned an error #404 (Not Found) for url: http://localhost:8983/solr/example_files/update?commit=true`); fair enough
- tried installing blacklight by cloning `https://github.com/projectblacklight/blacklight`, then following the "Installation" instructions from [README.md](https://github.com/projectblacklight/blacklight/blob/master/README.md); got nowhere
- tried installing blacklight by running `rails new blacklight_test -m https://raw.github.com/projectblacklight/blacklight/master/template.demo.rb` (found out about that in #2045), which seems to have worked
  - edited `config/environments/development.rb` to allow connecting from outside the VM
  - went to the address and found an error message titled `Blacklight::Exceptions::InvalidRequest in CatalogController#index`
  - reading further, the cause seems to be: `"error":{"msg":"sort param field can't be found: pub_date_si","code":400}`, which looks like it might (or might not?) fit in with this Issue here...

FWIW, the Solr log matches:

```
1252617 [qtp710714889-15] ERROR org.apache.solr.core.SolrCore  – org.apache.solr.common.SolrException: sort param field can't be found: pub_date_si
```

If I'm corectly understanding your conversation above, trying to go "the hard way" instead won't solve this, so now I'm stumped about how to get Blacklight to work :-(
