### ISSUE TITLE
NameError in CatalogController#index 

### ISSUE THREAD

**Issue by stefan-langenmaier** [projectblacklight/blacklight#1714]
Hi,

I'm trying to follow the Quickstart guide in the wiki to explore blacklight a little. That said I'm quite new. :)

I  have:

```
ruby -v
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]
```

```
rails -v
Rails 5.0.3
```

```
java -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-1~bpo8+1-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
```

And I run:

```
rails new blacklightapp
cd blacklightapp

gem install solr_wrapper
gem install devise devise-guests  this seems to be missing in the doc

echo "gem 'blacklight', \"~> 6.10\"" >> Gemfile # in the doc this is version 6.0
bundle install
rails generate blacklight:install --devise --marc --solr_version=latest
rake db:migrate
```

Starting solr wrapper worked fine and I can see the user interface but

```
rake solr:marc:index_test_data

** Invoke solr:marc:index_test_data (first_time)
** Invoke solr:environment (first_time)
** Execute solr:environment
** Execute solr:marc:index_test_data
** Invoke solr:marc:index:work (first_time)
** Invoke solr:environment 
** Execute solr:marc:index:work
rake aborted!
LoadError: cannot load such file -- ./app/models/marc_indexer
/usr/local/bundle/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:293:in `require'
/usr/local/bundle/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:293:in `block in require'
/usr/local/bundle/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:259:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:293:in `require'
/usr/local/bundle/gems/blacklight-marc-6.1.1/lib/railties/solr_marc.rake:51:in `block (4 levels) in <top (required)>'
/usr/local/bundle/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/usr/local/bundle/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/usr/local/bundle/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/usr/local/bundle/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/usr/local/bundle/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/usr/local/bundle/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/usr/local/bundle/gems/blacklight-marc-6.1.1/lib/railties/solr_marc.rake:37:in `block (3 levels) in <top (required)>'
/usr/local/bundle/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/usr/local/bundle/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/usr/local/bundle/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/usr/local/bundle/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/usr/local/bundle/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/usr/local/bundle/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/usr/local/bundle/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/usr/local/bundle/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/usr/local/bundle/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/usr/local/bundle/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/usr/local/bundle/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/usr/local/bundle/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/usr/local/bundle/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/usr/local/bundle/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/usr/local/bundle/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/usr/local/bundle/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/usr/local/bundle/bin/rake:17:in `load'
/usr/local/bundle/bin/rake:17:in `<main>'
Tasks: TOP => solr:marc:index:work
```

instead I ran and I can see some entries in the solr server afterwards

```
rake blacklight:index:seed
```

When I start the rails server and try to access the webinterface (http://192.168.99.100:3000/) I get the following error:

```
rails server
=> Booting Puma
=> Rails 5.0.3 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.9.1 (ruby 2.3.3-p222), codename: Private Caller
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop
Started GET "/" for 192.168.99.1 at 2017-06-06 14:14:18 +0000
Cannot render console from 192.168.99.1! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
  ActiveRecord::SchemaMigration Load (0.2ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Processing by CatalogController#index as HTML
Completed 500 Internal Server Error in 175ms (ActiveRecord: 0.0ms)


  
NameError (undefined local variable or method `search_state' for #<CatalogController:0x00000002d82e60>):
  
blacklight (6.10.0) app/controllers/concerns/blacklight/search_context.rb:49:in `find_search_session'
blacklight (6.10.0) app/controllers/concerns/blacklight/search_context.rb:30:in `current_search_session'
blacklight (6.10.0) app/controllers/concerns/blacklight/search_context.rb:35:in `set_current_search_session'
activesupport (5.0.3) lib/active_support/callbacks.rb:382:in `block in make_lambda'
activesupport (5.0.3) lib/active_support/callbacks.rb:150:in `block (2 levels) in halting_and_conditional'
actionpack (5.0.3) lib/abstract_controller/callbacks.rb:12:in `block (2 levels) in <module:Callbacks>'
activesupport (5.0.3) lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
activesupport (5.0.3) lib/active_support/callbacks.rb:454:in `block in call'
activesupport (5.0.3) lib/active_support/callbacks.rb:454:in `each'
activesupport (5.0.3) lib/active_support/callbacks.rb:454:in `call'
activesupport (5.0.3) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
activesupport (5.0.3) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
activesupport (5.0.3) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.3) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.0.3) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.0.3) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.0.3) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (5.0.3) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.0.3) lib/active_support/notifications.rb:164:in `instrument'
actionpack (5.0.3) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.0.3) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
activerecord (5.0.3) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (5.0.3) lib/abstract_controller/base.rb:126:in `process'
actionview (5.0.3) lib/action_view/rendering.rb:30:in `process'
actionpack (5.0.3) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (5.0.3) lib/action_controller/metal.rb:262:in `dispatch'
actionpack (5.0.3) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (5.0.3) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (5.0.3) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.3) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.3) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.3) lib/action_dispatch/routing/route_set.rb:725:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `catch'
warden (1.2.7) lib/warden/manager.rb:35:in `call'
rack (2.0.3) lib/rack/etag.rb:25:in `call'
rack (2.0.3) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.3) lib/rack/head.rb:12:in `call'
rack (2.0.3) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.3) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.0.3) lib/action_dispatch/middleware/cookies.rb:613:in `call'
activerecord (5.0.3) lib/active_record/migration.rb:553:in `call'
actionpack (5.0.3) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.3) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.3) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.3) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.3) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.3) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.3) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.3) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
web-console (3.5.1) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.5.1) lib/web_console/middleware.rb:20:in `block in call'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `catch'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `call'
actionpack (5.0.3) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.3) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.3) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.3) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.3) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.3) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.3) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.2.0) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.0.3) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.3) lib/rack/method_override.rb:22:in `call'
rack (2.0.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.3) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.3) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.3) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
railties (5.0.3) lib/rails/engine.rb:522:in `call'
puma (3.9.1) lib/puma/configuration.rb:224:in `call'
puma (3.9.1) lib/puma/server.rb:602:in `handle_request'
puma (3.9.1) lib/puma/server.rb:435:in `process_client'
puma (3.9.1) lib/puma/server.rb:299:in `block in run'
puma (3.9.1) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
  Rendering /usr/local/bundle/gems/actionpack-5.0.3/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout
  Rendering /usr/local/bundle/gems/actionpack-5.0.3/lib/action_dispatch/middleware/templates/rescues/_source.html.erb
  Rendered /usr/local/bundle/gems/actionpack-5.0.3/lib/action_dispatch/middleware/templates/rescues/_source.html.erb (4.5ms)
  Rendering /usr/local/bundle/gems/actionpack-5.0.3/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb
  Rendered /usr/local/bundle/gems/actionpack-5.0.3/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.5ms)
  Rendering /usr/local/bundle/gems/actionpack-5.0.3/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb
  Rendered /usr/local/bundle/gems/actionpack-5.0.3/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.7ms)
  Rendered /usr/local/bundle/gems/actionpack-5.0.3/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (144.0ms)
```

**Comment by jcoyne** [comment]
It appears to me that some parts of the generators did not run successfully


In blacklight-marc for example, the marc_indexer.rb should have been
created:
https://github.com/projectblacklight/blacklight-marc/blob/b7fde6c238dd5a1cd6a63aae17822ca18659efc7/lib/generators/blacklight/marc/install_generator.rb#L33

Can you show the output you got when you ran this command?

rails generate blacklight:install --devise --marc --solr_version=latest

- Justin


On Tue, Jun 6, 2017 at 7:18 AM, stefan-langenmaier <notifications@github.com

**Comment by stefan-langenmaier** [comment]
I'm sorry, it looks like the comand didn't run properly before. I tried it again (and also the db:migrate) and now the rails server responds without an error.

Thanks for your fast reply!
