### ISSUE TITLE
Implement SolrDocument#empty?

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/blacklight#1757]
On the 6.x branch.

Currently our method missing is catching SolrDocument#empty? and saying it's deprecated.  This is 
a problem, because `empty?` is an expected part of the ActiveModel interface. You can see this here:

https://github.com/rails/rails/blob/master/activemodel/lib/active_model/validator.rb?utf8=%E2%9C%93#L151

Alternatively it should not respond to `empty?`
```ruby
SolrDocument.new.respond_to?(:empty?)
=> true
```

```
     RuntimeError:
       DEPRECATION WARNING: Blacklight::Document#empty? is deprecated; use obj.to_h.empty? instead. (called from blank? at /Users/jcoyne/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.3/lib/active_support/core_ext/object/blank.rb:17)
     # /Users/jcoyne/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/deprecation-1.0.0/lib/deprecation/behaviors.rb:61:in `block in behaviors'
     # /Users/jcoyne/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/deprecation-1.0.0/lib/deprecation/reporting.rb:21:in `block (2 levels) in warn'
     # /Users/jcoyne/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/deprecation-1.0.0/lib/deprecation/reporting.rb:21:in `each'
     # /Users/jcoyne/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/deprecation-1.0.0/lib/deprecation/reporting.rb:21:in `block in warn'
     # /Users/jcoyne/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/deprecation-1.0.0/lib/deprecation/reporting.rb:20:in `tap'
     # /Users/jcoyne/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/deprecation-1.0.0/lib/deprecation/reporting.rb:20:in `warn'
     # /Users/jcoyne/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/blacklight-6.11.0/app/models/concerns/blacklight/document.rb:64:in `method_missing'
     # /Users/jcoyne/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.3/lib/active_support/core_ext/object/blank.rb:17:in `blank?'
     # /Users/jcoyne/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activemodel-5.1.3/lib/active_model/validator.rb:149:in `block in validate'
```

**Comment by jcoyne** [comment]
Fixed by #1758
