### ISSUE TITLE
Error on `bundle exec rake blacklight:server`

### ISSUE THREAD

**Issue by dkinzer** [projectblacklight/blacklight#1974]
Running this command on latest master commit I get the following error locally:

```
rake aborted!p.md5: |=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=--| 0% ( ETA: ??:??:?? )
SolrWrapper::SolrWrapperError: Unable to download solr from http://www.us.apache.org/dist/lucene/solr/7.5.0/solr-7.5.0.zip.md5
404 Not Found: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /dist/lucene/solr/7.5.0/solr-7.5.0.zip.md5 was not found on this server.</p>
</body></html>
tasks/blacklight.rake:57:in `block (2 levels) in <top (required)>'
/Users/dkinzer/.rbenv/versions/2.4.4/bin/bundle:23:in `load'
/Users/dkinzer/.rbenv/versions/2.4.4/bin/bundle:23:in `<main>'

Caused by:
OpenURI::HTTPError: 404 Not Found
```

**Comment by jcoyne** [comment]
It looks like you might have an out of date version of solr_wrapper.  Can you run `gem install solr_wrapper` and then try again?

**Comment by dkinzer** [comment]
hmm that didn't work but running `bundle update solr_wrapper` got it a bit farther field this time.  The new error is:

```
Failed to execute solr create: 
Specified configuration directory /Users/dkinzer/projects/blacklight/solr/conf not found!

. Further information may be available in /var/folders/l8/8ljsh0p103d9m4gg3866jlhh0000gp/T/solr-7.5.0/logs
/Users/dkinzer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/solr_wrapper-2.0.0/lib/solr_wrapper/instance.rb:321:in `exec'
/Users/dkinzer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/solr_wrapper-2.0.0/lib/solr_wrapper/instance.rb:158:in `create'
/Users/dkinzer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/solr_wrapper-2.0.0/lib/solr_wrapper/instanc
...
```

**Comment by dkinzer** [comment]
Also there are no logs so nothing to check.

**Comment by jcoyne** [comment]
That's interesting that it's looking for it's config in that location.   It should be using the directory specified here: https://github.com/projectblacklight/blacklight/blob/master/.solr_wrapper.yml#L11

**Comment by mejackreed** [comment]
@dkinzer do you perhaps have a local `.solr_wrapper.yml` file at `~/` that is overriding?

I would try removing the `Gemfile.lock` and `.internal_test_app` and start again. A fresh clone and install worked for me.

**Comment by dkinzer** [comment]
@mejackreed I do not have a such a file in my home directory.  I just tried deleting .internal_test_app folder and Gemfile.lock and rerunning `bundle install` and `bundle update solr` and still running into the same issue as before:

```
Done generating test app
rake aborted!
Failed to execute solr create: 
Specified configuration directory /Users/dkinzer/projects/blacklight/solr/conf not found!

. Further information may be available in /var/folders/l8/8ljsh0p103d9m4gg3866jlhh0000gp/T/solr-7.5.0/logs
tasks/blacklight.rake:56:in `block (3 levels) in <top (required)>'

```

**Comment by jcoyne** [comment]
@dkinzer can you show us the full output including the command that you are running?

**Comment by dkinzer** [comment]
@jcoyne here is a gist of the output: https://gist.github.com/a9ba07ecc3132e67f09d3eed67ebe54b

Here is the command I run plush some extra ouput:
```
dkinzer 14:58 [~/projects/blacklight]
(blacklight) ((v7.0.0.rc1)) > bundle exec rake blacklight:server --trace > output
** Invoke blacklight:server (first_time)
** Execute blacklight:server
** Invoke engine_cart:generate (first_time)
** Invoke engine_cart:setup (first_time)
** Execute engine_cart:setup
** Execute engine_cart:generate
** Invoke engine_cart:create_test_rails_app (first_time)
** Invoke engine_cart:setup 
** Execute engine_cart:create_test_rails_app
/Users/dkinzer/.rbenv/versions/2.4.4/lib/ruby/2.4.0/fileutils.rb:120: warning: conflicting chdir during another chdir block
** Invoke engine_cart:inject_gemfile_extras (first_time)
** Invoke engine_cart:setup 
** Execute engine_cart:inject_gemfile_extras
rake aborted!
Failed to execute solr create: 
Specified configuration directory /Users/dkinzer/projects/blacklight/solr/conf not found!

. Further information may be available in /var/folders/l8/8ljsh0p103d9m4gg3866jlhh0000gp/T/solr-7.5.0/logs
/Users/dkinzer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/solr_wrapper-2.0.0/lib/solr_wrapper/instance.rb:321:in `exec'
/Users/dkinzer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/solr_wrapper-2.0.0/lib/solr_wrapper/instance.rb:158:in `create'
/Users/dkinzer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/solr_wrapper-2.0.0/lib/solr_wrapper/instance.rb:215:in `with_collection'
tasks/blacklight.rake:56:in `block (3 levels) in <top (required)>'
/Users/dkinzer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/solr_wrapper-2.0.0/lib/solr_wrapper/instance.rb:64:in `wrap'
/Users/dkinzer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/solr_wrapper-2.0.0/lib/solr_wrapper.rb:43:in `wrap'
tasks/blacklight.rake:55:in `block (2 levels) in <top (required)>'
/Users/dkinzer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `block in execute'
/Users/dkinzer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `each'
/Users/dkinzer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `execute'
/Users/dkinzer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
/Users/dkinzer/.rbenv/versions/2.4.4/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/Users/dkinzer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
/Users/dkinzer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/task.rb:182:in `invoke'
/Users/dkinzer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:160:in `invoke_task'
/Users/dkinzer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/dkinzer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `each'
/Users/dkinzer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block in top_level'
/Users/dkinzer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:125:in `run_with_threads'
/Users/dkinzer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:110:in `top_level'
/Users/dkinzer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:83:in `block in run'
/Users/dkinzer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/dkinzer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/application.rb:80:in `run'
/Users/dkinzer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/Users/dkinzer/.rbenv/versions/2.4.4/bin/rake:23:in `load'
/Users/dkinzer/.rbenv/versions/2.4.4/bin/rake:23:in `<top (required)>'
/Users/dkinzer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
/Users/dkinzer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
/Users/dkinzer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
/Users/dkinzer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
/Users/dkinzer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/dkinzer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/dkinzer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/Users/dkinzer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
/Users/dkinzer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/Users/dkinzer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
/Users/dkinzer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
/Users/dkinzer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/Users/dkinzer/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
/Users/dkinzer/.rbenv/versions/2.4.4/bin/bundle:23:in `load'
/Users/dkinzer/.rbenv/versions/2.4.4/bin/bundle:23:in `<main>'
```

**Comment by dkinzer** [comment]
ok, so I've tried completely removing ruby version 2.4.4 then installing bundler and and running bundle install so everything is new and I'm still getting this issue.  Not sure what else I could do.

**Comment by jcoyne** [comment]
What's in the output file?

**Comment by dkinzer** [comment]
The issue was that I was not using the latest blacklight.  Thanks @jcoyne for helping me resolve that.
