### ISSUE TITLE
NoMethodError where for Blacklight::Search:Module

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/blacklight#2025]
```
[df2905a4-7800-4a7e-96d6-e87343608194] NoMethodError (undefined method `where' for Blacklight::Search:Module):
[df2905a4-7800-4a7e-96d6-e87343608194]
[df2905a4-7800-4a7e-96d6-e87343608194] /Users/jcoyne/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/blacklight-908fab0c3a87/app/controllers/concerns/blacklight/controller.rb:98:in `searches_from_history'
[df2905a4-7800-4a7e-96d6-e87343608194] /Users/jcoyne/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/blacklight-908fab0c3a87/app/controllers/concerns/blacklight/search_context.rb:85:in `find_or_initialize_search_session_from_params'
[df2905a4-7800-4a7e-96d6-e87343608194] /Users/jcoyne/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/blacklight-908fab0c3a87/app/controllers/concerns/blacklight/search_context.rb:53:in `find_search_session'
[df2905a4-7800-4a7e-96d6-e87343608194] /Users/jcoyne/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/blacklight-908fab0c3a87/app/controllers/concerns/blacklight/search_context.rb:32:in `current_search_session'
[df2905a4-7800-4a7e-96d6-e87343608194] /Users/jcoyne/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/blacklight-908fab0c3a87/app/controllers/concerns/blacklight/search_context.rb:37:in `set_current_search_session'
```

**Comment by jcoyne** [comment]
Rails has "helpfully" created that class for me: https://github.com/rails/rails/issues/34397 🤕
