### ISSUE TITLE
Running tests locally?

### ISSUE THREAD

**Issue by jrochkind** [projectblacklight/blacklight#2195]
Does anyone have a way to run tests locally on current blacklight master, or are tests only runnable on travis? 

Currently (on f401bdf1966), if I try to run either `bundle exec rake` or `bundle exec rake engine_cart:generate`, I get a whole bunch of errors in console, which somehow don't seem to stop it from continuing... when it finally stops continuing, the last thing in the console is.. several different errors actually, not sure how they all relate to each other. 

```
Backtrace: /Users/jrochkind/.gem/ruby/2.5.3/gems/rsolr-2.2.1/lib/rsolr/client.rb:206:in `rescue in execute'
/Users/jrochkind/.gem/ruby/2.5.3/gems/rsolr-2.2.1/lib/rsolr/client.rb:196:in `execute'
/Users/jrochkind/.gem/ruby/2.5.3/gems/rsolr-2.2.1/lib/rsolr/client.rb:191:in `send_and_receive'
(eval):2:in `post'
/Users/jrochkind/.gem/ruby/2.5.3/gems/rsolr-2.2.1/lib/rsolr/client.rb:94:in `update'
/Users/jrochkind/.gem/ruby/2.5.3/gems/rsolr-2.2.1/lib/rsolr/client.rb:113:in `add'
/Users/jrochkind/code/blacklight/lib/railties/blacklight.rake:21:in `block (3 levels) in <top (required)>'
/Users/jrochkind/.gem/ruby/2.5.3/gems/rake-13.0.0/lib/rake/task.rb:280:in `block in execute'
/Users/jrochkind/.gem/ruby/2.5.3/gems/rake-13.0.0/lib/rake/task.rb:280:in `each'
/Users/jrochkind/.gem/ruby/2.5.3/gems/rake-13.0.0/lib/rake/task.rb:280:in `execute'
/Users/jrochkind/.gem/ruby/2.5.3/gems/rake-13.0.0/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/Users/jrochkind/.gem/ruby/2.5.3/gems/rsolr-2.2.1/lib/rsolr/client.rb:206:in `rescue in execute'
/Users/jrochkind/.gem/ruby/2.5.3/gems/rsolr-2.2.1/lib/rsolr/client.rb:196:in `execute'
/Users/jrochkind/.gem/ruby/2.5.3/gems/rsolr-2.2.1/lib/rsolr/client.rb:191:in `send_and_receive'
(eval):2:in `post'
/Users/jrochkind/.gem/ruby/2.5.3/gems/rsolr-2.2.1/lib/rsolr/client.rb:94:in `update'
/Users/jrochkind/.gem/ruby/2.5.3/gems/rsolr-2.2.1/lib/rsolr/client.rb:113:in `add'
/Users/jrochkind/code/blacklight/lib/railties/blacklight.rake:21:in `block (3 levels) in <top (required)>'
/Users/jrochkind/.gem/ruby/2.5.3/gems/rake-13.0.0/exe/rake:27:in `<top (required)>'

Caused by:
Faraday::ResourceNotFound: the server responded with status 404
/Users/jrochkind/.gem/ruby/2.5.3/gems/faraday-0.17.0/lib/faraday/response/raise_error.rb:8:in `on_complete'
/Users/jrochkind/.gem/ruby/2.5.3/gems/faraday-0.17.0/lib/faraday/response.rb:9:in `block in call'
/Users/jrochkind/.gem/ruby/2.5.3/gems/faraday-0.17.0/lib/faraday/response.rb:61:in `on_complete'
/Users/jrochkind/.gem/ruby/2.5.3/gems/faraday-0.17.0/lib/faraday/response.rb:8:in `call'
/Users/jrochkind/.gem/ruby/2.5.3/gems/faraday-0.17.0/lib/faraday/rack_builder.rb:143:in `build_response'
/Users/jrochkind/.gem/ruby/2.5.3/gems/faraday-0.17.0/lib/faraday/connection.rb:387:in `run_request'
/Users/jrochkind/.gem/ruby/2.5.3/gems/faraday-0.17.0/lib/faraday/connection.rb:175:in `post'
/Users/jrochkind/.gem/ruby/2.5.3/gems/rsolr-2.2.1/lib/rsolr/client.rb:197:in `execute'
/Users/jrochkind/.gem/ruby/2.5.3/gems/rsolr-2.2.1/lib/rsolr/client.rb:191:in `send_and_receive'
(eval):2:in `post'
/Users/jrochkind/.gem/ruby/2.5.3/gems/rsolr-2.2.1/lib/rsolr/client.rb:94:in `update'
/Users/jrochkind/.gem/ruby/2.5.3/gems/rsolr-2.2.1/lib/rsolr/client.rb:113:in `add'
/Users/jrochkind/code/blacklight/lib/railties/blacklight.rake:21:in `block (3 levels) in <top (required)>'
/Users/jrochkind/.gem/ruby/2.5.3/gems/rake-13.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => blacklight:index:seed
(See full trace by running task with --trace)
/Users/jrochkind/.rubies/ruby-2.5.3/bin/ruby -I/Users/jrochkind/.gem/ruby/2.5.3/gems/rspec-core-3.9.0/lib:/Users/jrochkind/.gem/ruby/2.5.3/gems/rspec-support-3.9.0/lib /Users/jrochkind/.gem/ruby/2.5.3/gems/rspec-core-3.9.0/exe/rspec --pattern spec/\*\*/\*_spec.rb
Bundler could not find compatible versions for gem "sprockets":
  In snapshot (Gemfile.lock):
    sprockets (= 4.0.0)

  In Gemfile:
    sass-rails (~> 5) was resolved to 5.1.0, which depends on
      sprockets (< 4.0, >= 2.8)

    rails (~> 6.0.0) was resolved to 6.0.0, which depends on
      sprockets-rails (>= 2.0.0) was resolved to 3.2.1, which depends on
        sprockets (>= 3.0.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
/Users/jrochkind/.rubies/ruby-2.5.3/bin/ruby -I/Users/jrochkind/.gem/ruby/2.5.3/gems/rspec-core-3.9.0/lib:/Users/jrochkind/.gem/ruby/2.5.3/gems/rspec-support-3.9.0/lib /Users/jrochkind/.gem/ruby/2.5.3/gems/rspec-core-3.9.0/exe/rspec --pattern spec/\*\*/\*_spec.rb failed
```

**Comment by dkinzer** [comment]
@jrochkind for now run `bundle exec rake engine_cart:server` and then you should be able to do do `bundle exec rspec` from inside the internal app (`cd ./.internal_app`)

**Comment by jrochkind** [comment]
@dkinzer thanks! To avoid confusion I did a fresh checkout of the blacklight repo. 

On a fresh checkout, if I run `bundle exec rake engine_cart:server`, i get a bunch of errors in the console, the last section of which right before it finishes is:

<details>
<summary>Click to expand</summary>

```
Bundler could not find compatible versions for gem "sprockets":
  In snapshot (Gemfile.lock):
    sprockets (= 4.0.0)

  In Gemfile:
    sass-rails (~> 5) was resolved to 5.1.0, which depends on
      sprockets (< 4.0, >= 2.8)

    rails (~> 6.0.0) was resolved to 6.0.0, which depends on
      sprockets-rails (>= 2.0.0) was resolved to 3.2.1, which depends on
        sprockets (>= 3.0.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
Done generating test app
warning: parser/current is loading parser/ruby25, which recognizes
warning: 2.5.7-compliant syntax, but you are running 2.5.3.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
=> Booting Puma
=> Rails 6.0.0 application starting in development
=> Run `rails server --help` for more startup options
RAILS_ENV=development environment is not defined in config/webpacker.yml, falling back to production environment
Exiting
Traceback (most recent call last):
	51: from bin/rails:4:in `<main>'
	50: from bin/rails:4:in `require'
	49: from /Users/jrochkind/.gem/ruby/2.5.3/gems/railties-6.0.0/lib/rails/commands.rb:18:in `<top (required)>'
	48: from /Users/jrochkind/.gem/ruby/2.5.3/gems/railties-6.0.0/lib/rails/command.rb:46:in `invoke'
	47: from /Users/jrochkind/.gem/ruby/2.5.3/gems/railties-6.0.0/lib/rails/command/base.rb:65:in `perform'
	46: from /Users/jrochkind/.gem/ruby/2.5.3/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	45: from /Users/jrochkind/.gem/ruby/2.5.3/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	44: from /Users/jrochkind/.gem/ruby/2.5.3/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	43: from /Users/jrochkind/.gem/ruby/2.5.3/gems/railties-6.0.0/lib/rails/commands/server/server_command.rb:138:in `perform'
	42: from /Users/jrochkind/.gem/ruby/2.5.3/gems/railties-6.0.0/lib/rails/commands/server/server_command.rb:138:in `tap'
	41: from /Users/jrochkind/.gem/ruby/2.5.3/gems/railties-6.0.0/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	40: from /Users/jrochkind/.gem/ruby/2.5.3/gems/railties-6.0.0/lib/rails/commands/server/server_command.rb:37:in `start'
	39: from /Users/jrochkind/.gem/ruby/2.5.3/gems/railties-6.0.0/lib/rails/commands/server/server_command.rb:77:in `log_to_stdout'
	38: from /Users/jrochkind/.gem/ruby/2.5.3/gems/rack-2.0.7/lib/rack/server.rb:354:in `wrapped_app'
	37: from /Users/jrochkind/.gem/ruby/2.5.3/gems/rack-2.0.7/lib/rack/server.rb:219:in `app'
	36: from /Users/jrochkind/.gem/ruby/2.5.3/gems/rack-2.0.7/lib/rack/server.rb:319:in `build_app_and_options_from_config'
	35: from /Users/jrochkind/.gem/ruby/2.5.3/gems/rack-2.0.7/lib/rack/builder.rb:40:in `parse_file'
	34: from /Users/jrochkind/.gem/ruby/2.5.3/gems/rack-2.0.7/lib/rack/builder.rb:49:in `new_from_string'
	33: from /Users/jrochkind/.gem/ruby/2.5.3/gems/rack-2.0.7/lib/rack/builder.rb:49:in `eval'
	32: from config.ru:in `<main>'
	31: from config.ru:in `new'
	30: from /Users/jrochkind/.gem/ruby/2.5.3/gems/rack-2.0.7/lib/rack/builder.rb:55:in `initialize'
	29: from /Users/jrochkind/.gem/ruby/2.5.3/gems/rack-2.0.7/lib/rack/builder.rb:55:in `instance_eval'
	28: from config.ru:3:in `block in <main>'
	27: from config.ru:3:in `require_relative'
	26: from /Users/jrochkind/code/blacklight/.internal_test_app/config/environment.rb:5:in `<top (required)>'
	25: from /Users/jrochkind/.gem/ruby/2.5.3/gems/railties-6.0.0/lib/rails/application.rb:363:in `initialize!'
	24: from /Users/jrochkind/.gem/ruby/2.5.3/gems/railties-6.0.0/lib/rails/initializable.rb:60:in `run_initializers'
	23: from /Users/jrochkind/.rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
	22: from /Users/jrochkind/.rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
	21: from /Users/jrochkind/.rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
	20: from /Users/jrochkind/.rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:347:in `call'
	19: from /Users/jrochkind/.rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:347:in `each'
	18: from /Users/jrochkind/.rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
	17: from /Users/jrochkind/.rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
	16: from /Users/jrochkind/.rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	15: from /Users/jrochkind/.rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
	14: from /Users/jrochkind/.gem/ruby/2.5.3/gems/railties-6.0.0/lib/rails/initializable.rb:61:in `block in run_initializers'
	13: from /Users/jrochkind/.gem/ruby/2.5.3/gems/railties-6.0.0/lib/rails/initializable.rb:32:in `run'
	12: from /Users/jrochkind/.gem/ruby/2.5.3/gems/railties-6.0.0/lib/rails/initializable.rb:32:in `instance_exec'
	11: from /Users/jrochkind/.gem/ruby/2.5.3/gems/webpacker-4.0.7/lib/webpacker/railtie.rb:84:in `block in <class:Engine>'
	10: from /Users/jrochkind/.gem/ruby/2.5.3/gems/webpacker-4.0.7/lib/webpacker.rb:27:in `bootstrap'
	 9: from /Users/jrochkind/.gem/ruby/2.5.3/gems/webpacker-4.0.7/lib/webpacker/commands.rb:14:in `bootstrap'
	 8: from /Users/jrochkind/.gem/ruby/2.5.3/gems/webpacker-4.0.7/lib/webpacker/manifest.rb:18:in `refresh'
	 7: from /Users/jrochkind/.gem/ruby/2.5.3/gems/webpacker-4.0.7/lib/webpacker/manifest.rb:83:in `load'
	 6: from /Users/jrochkind/.gem/ruby/2.5.3/gems/webpacker-4.0.7/lib/webpacker/configuration.rb:47:in `public_manifest_path'
	 5: from /Users/jrochkind/.gem/ruby/2.5.3/gems/webpacker-4.0.7/lib/webpacker/configuration.rb:43:in `public_output_path'
	 4: from /Users/jrochkind/.gem/ruby/2.5.3/gems/webpacker-4.0.7/lib/webpacker/configuration.rb:39:in `public_path'
	 3: from /Users/jrochkind/.gem/ruby/2.5.3/gems/webpacker-4.0.7/lib/webpacker/configuration.rb:80:in `fetch'
	 2: from /Users/jrochkind/.gem/ruby/2.5.3/gems/webpacker-4.0.7/lib/webpacker/configuration.rb:84:in `data'
	 1: from /Users/jrochkind/.gem/ruby/2.5.3/gems/webpacker-4.0.7/lib/webpacker/configuration.rb:87:in `load'
/Users/jrochkind/.gem/ruby/2.5.3/gems/webpacker-4.0.7/lib/webpacker/configuration.rb:91:in `rescue in load': Webpacker configuration file not found /Users/jrochkind/code/blacklight/.internal_test_app/config/webpacker.yml. Please run rails webpacker:install Error: No such file or directory @ rb_sysopen - /Users/jrochkind/code/blacklight/.internal_test_app/config/webpacker.yml (RuntimeError)
```
</details>

If I go ahead anyway and try to `cd ./internal_app` and `bundle exec rspec`, I get 

<details>
<summary>these errors</summary>

```
An error occurred while loading ./spec/models/search_builder_spec.rb. - Did you mean?
                    rspec ./spec/models/user_spec.rb

Failure/Error: require 'rails_helper'

LoadError:
  cannot load such file -- rails_helper
# ./spec/models/search_builder_spec.rb:1:in `require'
# ./spec/models/search_builder_spec.rb:1:in `<top (required)>'

An error occurred while loading ./spec/models/user_spec.rb. - Did you mean?
                    rspec ./spec/models/search_builder_spec.rb

Failure/Error: require 'rails_helper'

LoadError:
  cannot load such file -- rails_helper
# ./spec/models/user_spec.rb:1:in `require'
# ./spec/models/user_spec.rb:1:in `<top (required)>'
No examples found.


Finished in 0.00006 seconds (files took 0.1153 seconds to load)
0 examples, 0 failures, 2 errors occurred outside of examples
```
</details>

**Comment by dkinzer** [comment]
@jrochkind I didn't run into these issues locally... I thing I forgot to not is I ran bundle install also I'm using ruby --version 2.6.5 on my local, maybe that made all the difference (don't know)

**Comment by dkinzer** [comment]
@jrochkind also, how do you make the code block collapsible like that?

**Comment by jkeck** [comment]
@dkinzer see https://gist.github.com/joyrexus/16041f2426450e73f5df9391f7f7ae5f for an example (click the `Raw` button)

**Comment by mejackreed** [comment]
I'm seeing some issues with running the recently release Solr v8.3.0. I've found you can get up and going by creating a local `.solr_wrapper.yml` file like so:

```yml
# Place any default configuration for solr_wrapper here
# port: 8983
collection:
  dir: lib/generators/blacklight/templates/solr/conf/
  name: blacklight-core
version: 8.2.0
```

**Comment by jrochkind** [comment]
I don't _think_ my problems are solr-version related, the error messages are about things like `Bundler could not find compatible versions for gem "sprockets"` and `Webpacker configuration file not found /Users/jrochkind/code/blacklight/.internal_test_app/config/webpacker.yml. Please run rails webpacker:install`

But just to rule it out, I'll try it... should the .solr_wrapper.yml be at blacklight root, or at `.internal_test_app/` after it's been generated? Oops, the problem with the latter is I can't _get_ it generated succesfully, I think it's aborting in the middle. 

I really don't think it's the solr version. 

I wonder if some of you for whom it's working, have it working cause of things already set up in existing checkouts that wouldn't work on a new checkout. 

If anyone wanted to try a fresh git repo clone and see if you can get local test runs to work, or if my problem reproduces for you, I'd appreciate it!

@cdmo ?

**Comment by mjgiarlo** [comment]
@jrochkind @jkeck @dkinzer @mejackreed This should now be addressed with the latest code in `master` and the documentation here: https://github.com/projectblacklight/blacklight/wiki/Testing-and-Developing-Blacklight
