### ISSUE TITLE
trouble with solr_wrapper in quickstart

### ISSUE THREAD

**Issue by pdennis** [projectblacklight/blacklight#2216]
Trying to run through the quickstart process in WSL on windows 10. I'm not particularly familiar with ruby or rails, so it might be something simple here. 

Basically, I'm unable to start solr_wrapper. Here's the output I receive. I have tried a few things (removing and reinstalling solr_wrapper, rebooting, etc), but don't want to mess around too much lest I cause more damage than I fix. 

Thanks in advance, here's my terminal output. It does hang on the "Starting Solr 8.3.0 on port 8983" message for quite a while every time i try to run it. 

Thanks in advance

` pdennis@DESKTOP-RI5MKTM:~/bin/blacklight/projects/search_app$bundle exec solr_wrapper
Starting Solr 8.3.0 on port 8983 ... bundler: failed to load command: solr_wrapper (/home/pdennis/.rbenv/versions/2.5.3/bin/solr_wrapper)
RuntimeError: Not started yet
  /home/pdennis/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/solr_wrapper-2.1.0/lib/solr_wrapper/instance.rb:152:in `block in create'
  /home/pdennis/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
  /home/pdennis/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
  /home/pdennis/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
  /home/pdennis/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/solr_wrapper-2.1.0/lib/solr_wrapper/instance.rb:151:in `create'
  /home/pdennis/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/solr_wrapper-2.1.0/lib/solr_wrapper/instance.rb:215:in `with_collection'
  /home/pdennis/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/solr_wrapper-2.1.0/exe/solr_wrapper:114:in `block in <top (required)>'
  /home/pdennis/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/solr_wrapper-2.1.0/lib/solr_wrapper/instance.rb:64:in `wrap'
  /home/pdennis/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/solr_wrapper-2.1.0/exe/solr_wrapper:113:in `<top (required)>'
  /home/pdennis/.rbenv/versions/2.5.3/bin/solr_wrapper:23:in `load'
  /home/pdennis/.rbenv/versions/2.5.3/bin/solr_wrapper:23:in `<top (required)>'`

**Comment by mejackreed** [comment]
Hi @pdennis , do you have Java installed? If so which version?

**Comment by chrisnaadhi** [comment]
I'm also troubling with this

`Starting Solr 8.4.1 on port 8983 ... bundler: failed to load command: solr_wrapper (/home/chrisna/.rbenv/versions/2.6.5/bin/solr_wrapper)
RuntimeError: Not started yet
  /home/chrisna/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/solr_wrapper-2.2.0/lib/solr_wrapper/instance.rb:152:in `block in create'
  /home/chrisna/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
  /home/chrisna/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
  /home/chrisna/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
  /home/chrisna/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/solr_wrapper-2.2.0/lib/solr_wrapper/instance.rb:151:in `create'
  /home/chrisna/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/solr_wrapper-2.2.0/lib/solr_wrapper/instance.rb:215:in `with_collection'
  /home/chrisna/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/solr_wrapper-2.2.0/exe/solr_wrapper:114:in `block in <top (required)>'
  /home/chrisna/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/solr_wrapper-2.2.0/lib/solr_wrapper/instance.rb:64:in `wrap'
  /home/chrisna/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/solr_wrapper-2.2.0/exe/solr_wrapper:113:in `<top (required)>'
  /home/chrisna/.rbenv/versions/2.6.5/bin/solr_wrapper:23:in `load'
  /home/chrisna/.rbenv/versions/2.6.5/bin/solr_wrapper:23:in `<top (required)>'` 

my ruby :
`ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]`
my rails : 
`Rails 5.2.4.1`
my java : 
`java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)`
javac : 
`javac 1.8.0_241`

**Comment by mejackreed** [comment]
Hi @chrisnaadhi . 

Can you try adding `gem 'solr_wrapper'` to your `Gemfile` and then `bundle install`?

I'll look at updating the documentation to make sure it gets resolved.

**Comment by fontanka16** [comment]
I am stuck at the same issue. How important is the Java Version? I am in Java 11

**Comment by dvhassel** [comment]
Same for me right now:

```
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~20.04-b01)
OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode)
```

`Rails 5.2.4.4`

`ruby 2.7.2p137 `

Any suggestions?

**Comment by varshinichowdary27** [comment]
any update on this issue? i am still facing the issue with 
ruby 3.1.2
rails 7
java 11
