### ISSUE TITLE
Bookmark page is causing an error when viewing using add_show_tools_partial

### ISSUE THREAD

**Issue by mejackreed** [projectblacklight/blacklight#2400]
Introduced in Blacklight v7.12.0 via https://github.com/projectblacklight/blacklight/commit/7651c768c8605fd1fdf400c3d10e50f559078fc5

`render_show_doc_actions_method_from_blacklight?` is always evaluating `true` for `add_show_tools_partial`.

This is one reason for the GeoBlacklight build to be failing: https://github.com/geoblacklight/geoblacklight/blob/main/lib/generators/geoblacklight/templates/catalog_controller.rb#L246-L250 (and for a Bookmarks page in GeoBlacklight to cause an error to render).

I'm not 💯 sure of the fix here, but I'm thinking `render_show_doc_actions_method_from_blacklight?` needs to be more clever?

**Comment by cbeer** [comment]
What's the error?

**Comment by mejackreed** [comment]
The first error encountered is:

```
  1) Blacklight Bookmarks index has created bookmarks
     Failure/Error: visit bookmarks_path
     
     ActionView::Template::Error:
       undefined method `references' for #<Array:0x000055aea7aba698>
     # ./.internal_test_app/app/controllers/catalog_controller.rb:246:in `block (2 levels) in <class:CatalogController>'
     # ./spec/features/bookmarks_spec.rb:8:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # NoMethodError:
     #   undefined method `references' for #<Array:0x000055aea7aba698>
     #   ./.internal_test_app/app/controllers/catalog_controller.rb:246:in `block (2 levels) in <class:CatalogController>'
```
Via: https://app.circleci.com/pipelines/github/geoblacklight/geoblacklight/601/workflows/3116da8b-be2a-4214-a2e8-2f7ee2773d9c/jobs/4630

This is the case because a configured `add_show_tools_partial` `document` is now an array, and not a document.
