### ISSUE TITLE
newly created app from quickstart template has error on first launch, undefined `search_state`

### ISSUE THREAD

**Issue by jrochkind** [projectblacklight/blacklight#2413]
Did `rails new search_app -m https://raw.github.com/projectblacklight/blacklight/master/template.demo.rb` as per quickstart guide. 

cd'd into new_search app and `rails server`. 

Accesed app at `https://localhost:3000`. 

Got this error:

```
NameError (undefined local variable or method `search_state' for #<CatalogController:0x00007ff98d1c53c0>
Did you mean?  search_session):

blacklight (7.14.0) app/controllers/concerns/blacklight/search_context.rb:53:in `find_search_session'
blacklight (7.14.0) app/controllers/concerns/blacklight/search_context.rb:32:in `current_search_session'
blacklight (7.14.0) app/controllers/concerns/blacklight/search_context.rb:37:in `set_current_search_session'
activesupport (6.0.3.4) lib/active_support/callbacks.rb:428:in `block in make_lambda'
```

rails 6.0.3.4
blacklight 7.14.0

Was actually trying to reproduce a *different* error I'm having in my app with blacklight and rails 6.1. But didn't get there, got stopped by this! And then realized I wasn't in rails 6.1 anyway here! But anyway, this seems like it's own thing.

**Comment by jrochkind** [comment]
Assuming this is reproducible by others, one question is why CI wouldn't catch this.

**Comment by jrochkind** [comment]
actually i'm gonna close this for now, it's possible i'm getting confused with something.
