### ISSUE TITLE
ActionView::Template::Error (undefined method `new' for true:TrueClass):

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/blacklight#2533]
```
[1, 9] in /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/blacklight-d060af02c815/app/views/catalog/_facets.html.erb
   1: <% # container for facet groups -%>
   2: <% byebug %>
=> 3: <% blacklight_config.facet_group_names.each do |groupname| %>
   4:   <%= render Blacklight::Response::FacetGroupComponent.new(
   5:     response: @response,
   6:     id: groupname,
   7:     fields: blacklight_config.facet_fields_in_group(groupname),
   8:     title: groupname.present? ? t("blacklight.search.facets-#{groupname}.title") : t('blacklight.search.facets.title')) %>
   9: <% end %>
(byebug) blacklight_config.facet_group_names
[nil]
```

backtrace:
```
/Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/blacklight-d060af02c815/app/components/blacklight/facet_component.rb:28:in `call'
/Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/view_component-2.43.1/lib/view_component/compiler.rb:83:in `render_template_for'
/Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/view_component-2.43.1/lib/view_component/base.rb:90:in `render_in'
/Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/view_component-2.43.1/lib/view_component/collection.rb:17:in `block in render_in'
/Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/view_component-2.43.1/lib/view_component/collection.rb:16:in `map'
/Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/view_component-2.43.1/lib/view_component/collection.rb:16:in `render_in'
/Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.4.1/lib/action_view/helpers/rendering_helper.rb:43:in `render'
/Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/view_component-2.43.1/lib/view_component/base.rb:143:in `render'
/Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/blacklight-d060af02c815/app/components/blacklight/response/facet_group_component.html.erb:25:in `block in call'
/Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.4.1/lib/action_view/helpers/capture_helper.rb:45:in `block in capture'
/Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.4.1/lib/action_view/helpers/capture_helper.rb:209:in `with_output_buffer'
/Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.4.1/lib/action_view/helpers/capture_helper.rb:45:in `capture'
/Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.4.1/lib/action_view/helpers/tag_helper.rb:310:in `content_tag'
/Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/blacklight-d060af02c815/app/components/blacklight/response/facet_group_component.html.erb:2:in `call'
/Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/view_component-2.43.1/lib/view_component/compiler.rb:83:in `render_template_for'
/Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/view_component-2.43.1/lib/view_component/base.rb:90:in `render_in'
/Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.4.1/lib/action_view/helpers/rendering_helper.rb:43:in `render'
/Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/blacklight-d060af02c815/app/views/catalog/_facets.html.erb:3:in `block in ___sers_jcoyne____rbenv_versions_______lib_ruby_gems_______bundler_gems_blacklight_d___af__c____app_views_catalog__facets_html_erb__2888783678430910214_85540'
/Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/blacklight-d060af02c815/app/views/catalog/_facets.html.erb:2:in `each'
/Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/blacklight-d060af02c815/app/views/catalog/_facets.html.erb:2:in `___sers_jcoyne____rbenv_versions_______lib_ruby_gems_______bundler_gems_blacklight_d___af__c____app_views_catalog__facets_html_erb__2888783678430910214_85540'
/Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.4.1/lib/action_view/base.rb:247:in `public_send'
/Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.4.1/lib/action_view/base.rb:247:in `_run'
/Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.4.1/lib/action_view/template.rb:154:in `block in render'
/Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/notifications.rb:205:in `instrument'
/Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.4.1/lib/action_view/template.rb:345:in `instrument_render_template'
/Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.4.1/lib/action_view/template.rb:152:in `render'
/Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.4.1/lib/action_view/renderer/partial_renderer.rb:285:in `block in render_partial_template'
/Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/notifications.rb:203:in `block in instrument'
/Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/notifications.rb:203:in `instrument'
/Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.4.1/lib/action_view/renderer/partial_renderer.rb:280:in `render_partial_template'
/Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.4.1/lib/action_view/renderer/partial_renderer.rb:271:in `render'
/Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.4.1/lib/action_view/renderer/renderer.rb:81:in `render_partial_to_object'
/Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.4.1/lib/action_view/renderer/renderer.rb:53:in `render_partial'
/Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionview-6.1.4.1/lib/action_view/helpers/rendering_helper.rb:45:in `render'
/Users/jcoyne85/workspace/sul-dlss/argo/app/views/catalog/_search_sidebar.html.erb:1:in `_app_views_catalog__search_sidebar_html_erb__2579949769960538621_85520'
```

**Comment by jcoyne** [comment]
The fix for this is to remove `component: true` configuration from `add_facet_field` in `CatalogController`
