### ISSUE TITLE
Duplicate index_field when explicity specifying "id"

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/blacklight#2933]
```
An error occurred while loading ./spec/routing/report_routing_spec.rb.
Failure/Error: config.add_index_field "id", label: "DRUID"

RuntimeError:
  A index_field with the key id already exists.
# ./app/controllers/catalog_controller.rb:38:in `block in <class:CatalogController>'
# ./app/controllers/catalog_controller.rb:10:in `<class:CatalogController>'
# ./app/controllers/catalog_controller.rb:3:in `<top (required)>'
# ./app/controllers/report_controller.rb:3:in `<top (required)>'
# ./spec/routing/report_routing_spec.rb:5:in `<top (required)>'
```

**Comment by jcoyne** [comment]
Can't duplicate
