### ISSUE TITLE
Indexing MARC records step fails in Quickstart guide

### ISSUE THREAD

**Issue by mephillips-durham** [projectblacklight/blacklight#3081]
In the section for [Easy or Hard: After creating your new application](https://github.com/projectblacklight/blacklight/wiki/Quickstart#easy-or-hard-after-creating-your-new-application) I was able to start Solr using solr_wrapper. I was able to access the Solr web interface. I then tried the "Index some data" step and got this error:
```
vagrant@ubuntu-jammy:~$ cd projects/search_app/
vagrant@ubuntu-jammy:~/projects/search_app$ rake solr:marc:index_test_data
rake aborted!
LoadError: cannot load such file -- /home/vagrant/projects/search_app/app/models/marc_indexer
<internal:/home/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
<internal:/home/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
Tasks: TOP => solr:marc:index:work
(See full trace by running task with --trace)
```

The /home/vagrant/projects/search_app/app/models/marc_indexer file does not seem to be present. Searching using find from the home directory I can see these are present:
```
vagrant@ubuntu-jammy:~$ find . | grep marc_indexer
./.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/traject-3.8.1/lib/traject/indexer/marc_indexer.rb
./.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/blacklight-marc-8.1.0/lib/generators/blacklight/marc/templates/app/models/marc_indexer.rb
```

Is there a fault with the rake task for index_test_data or should I be located in a different directory to run the command, perhaps?

I followed the [Creating a new application the easy way](https://github.com/projectblacklight/blacklight/wiki/Quickstart#creating-a-new-application-the-easy-way). I see the "hard way" instructions include `rails generate blacklight:install --devise --marc --solr_version=latest` to generate blacklight-marc into the application, so perhaps that is missing from the easy method? I checked [here](https://github.com/projectblacklight/blacklight/blob/51d4f59385549e2031fafa616a1d5a039771bd57/template.demo.rb#L8) and there seems to be something about including blacklight-marc in the easy method. (Though I don't fully understand the ENV.fetch and whether it will take the --devise and --marc options or not.)

**Comment by bess** [comment]
I can confirm this bug on a mac, newly generated blacklight application, using lando for solr: 

```
be rake solr:marc:index_test_data
rake aborted!
ArgumentError: Traject::SolrJsonWriter: Neither solr.update_url nor solr.url set; need at least one (ArgumentError)

      raise ArgumentError.new("#{self.class.name}: Neither solr.update_url nor solr.url set; need at least one")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/Users/bess/.asdf/installs/ruby/3.2.0/bin/bundle:25:in `load'
/Users/bess/.asdf/installs/ruby/3.2.0/bin/bundle:25:in `<main>'
Tasks: TOP => solr:marc:index:work
(See full trace by running task with --trace)
```

I will see if I can figure it out.

**Comment by sopheck** [comment]
It's still an issue:

```
rake solr:marc:index_test_data
rake aborted!
LoadError: cannot load such file -- /home/sopheck/blacklight_projects/search_app/app/models/marc_indexer (LoadError)

Tasks: TOP => solr:marc:index:work
(See full trace by running task with --trace)
```

The app is running on Ubuntu 22.04 (WSL) with:
- `blacklight`: 8.9.0
- `blacklight_marc`: 8.1.4
- `solr_wrapper`: 4.1.3
- `ruby`: 3.4.3

Complete stack trace:

```
/home/sopheck/.local/share/mise/installs/ruby/3.4.3/lib/ruby/3.4.0/bundled_gems.rb:82:in 'Kernel.require'
/home/sopheck/.local/share/mise/installs/ruby/3.4.3/lib/ruby/3.4.0/bundled_gems.rb:82:in 'block (2 levels) in Kernel#replace_require'
/home/sopheck/.local/share/mise/installs/ruby/3.4.3/lib/ruby/gems/3.4.0/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in 'Kernel#require'
/home/sopheck/.local/share/mise/installs/ruby/3.4.3/lib/ruby/gems/3.4.0/gems/zeitwerk-2.7.2/lib/zeitwerk/core_ext/kernel.rb:34:in 'Kernel#require'
/home/sopheck/.local/share/mise/installs/ruby/3.4.3/lib/ruby/gems/3.4.0/gems/blacklight-marc-8.1.4/lib/railties/solr_marc.rake:51:in 'block (4 levels) in <main>'
/home/sopheck/.local/share/mise/installs/ruby/3.4.3/lib/ruby/gems/3.4.0/gems/rake-13.2.1/lib/rake/task.rb:281:in 'block in Rake::Task#execute'
/home/sopheck/.local/share/mise/installs/ruby/3.4.3/lib/ruby/gems/3.4.0/gems/rake-13.2.1/lib/rake/task.rb:281:in 'Array#each'
/home/sopheck/.local/share/mise/installs/ruby/3.4.3/lib/ruby/gems/3.4.0/gems/rake-13.2.1/lib/rake/task.rb:281:in 'Rake::Task#execute'
/home/sopheck/.local/share/mise/installs/ruby/3.4.3/lib/ruby/gems/3.4.0/gems/rake-13.2.1/lib/rake/task.rb:219:in 'block in Rake::Task#invoke_with_call_chain'
/home/sopheck/.local/share/mise/installs/ruby/3.4.3/lib/ruby/gems/3.4.0/gems/rake-13.2.1/lib/rake/task.rb:199:in 'Monitor#synchronize'
/home/sopheck/.local/share/mise/installs/ruby/3.4.3/lib/ruby/gems/3.4.0/gems/rake-13.2.1/lib/rake/task.rb:199:in 'Rake::Task#invoke_with_call_chain'
/home/sopheck/.local/share/mise/installs/ruby/3.4.3/lib/ruby/gems/3.4.0/gems/rake-13.2.1/lib/rake/task.rb:188:in 'Rake::Task#invoke'
/home/sopheck/.local/share/mise/installs/ruby/3.4.3/lib/ruby/gems/3.4.0/gems/rake-13.2.1/lib/rake/application.rb:188:in 'Rake::Application#invoke_task'
/home/sopheck/.local/share/mise/installs/ruby/3.4.3/lib/ruby/gems/3.4.0/gems/rake-13.2.1/lib/rake/application.rb:138:in 'block (2 levels) in Rake::Application#top_level'
/home/sopheck/.local/share/mise/installs/ruby/3.4.3/lib/ruby/gems/3.4.0/gems/rake-13.2.1/lib/rake/application.rb:138:in 'Array#each'
/home/sopheck/.local/share/mise/installs/ruby/3.4.3/lib/ruby/gems/3.4.0/gems/rake-13.2.1/lib/rake/application.rb:138:in 'block in Rake::Application#top_level'
/home/sopheck/.local/share/mise/installs/ruby/3.4.3/lib/ruby/gems/3.4.0/gems/rake-13.2.1/lib/rake/application.rb:147:in 'Rake::Application#run_with_threads'
/home/sopheck/.local/share/mise/installs/ruby/3.4.3/lib/ruby/gems/3.4.0/gems/rake-13.2.1/lib/rake/application.rb:132:in 'Rake::Application#top_level'
/home/sopheck/.local/share/mise/installs/ruby/3.4.3/lib/ruby/gems/3.4.0/gems/rake-13.2.1/lib/rake/application.rb:83:in 'block in Rake::Application#run'
/home/sopheck/.local/share/mise/installs/ruby/3.4.3/lib/ruby/gems/3.4.0/gems/rake-13.2.1/lib/rake/application.rb:214:in 'Rake::Application#standard_exception_handling'
/home/sopheck/.local/share/mise/installs/ruby/3.4.3/lib/ruby/gems/3.4.0/gems/rake-13.2.1/lib/rake/application.rb:80:in 'Rake::Application#run'
/home/sopheck/.local/share/mise/installs/ruby/3.4.3/lib/ruby/gems/3.4.0/gems/rake-13.2.1/exe/rake:27:in '<top (required)>'
/home/sopheck/.local/share/mise/installs/ruby/3.4.3/bin/rake:25:in 'Kernel#load'
/home/sopheck/.local/share/mise/installs/ruby/3.4.3/bin/rake:25:in '<main>'
Tasks: TOP => solr:marc:index:work
```

**Comment by sopheck** [comment]
I was able to resolve it with the following quick, though not particularly elegant, fix:

1. Create a symlink for `marc_indexer.rb`: I created a symlink for `marc_indexer.rb` in the `search_app/models/` directory. I used the following command:

```bash
ln -s ~/.local/share/mise/installs/ruby/3.4.3/lib/ruby/gems/3.4.0/gems/blacklight-marc-8.1.4/lib/generators/blacklight/marc/templates/marc_indexer.rb search_app/models/marc_indexer.rb
```

2. Copy `translations_map` from Blacklight: I copied the `callnumber_map.properties` file from the `blacklight-marc` gem directory into the `config/translation_maps/` directory of my app (needs to be created):

```bash
mkdir -p config/translation_maps

cp ~/.local/share/mise/installs/ruby/3.4.3/lib/ruby/gems/3.4.0/gems/blacklight-marc-8.1.4/lib/generators/blacklight/marc/templates/config/translation_maps/callnumber_map.properties config/translation_maps/
```

With these two steps, I was able to run the `rake solr:marc:index_test_data` task successfully. It's not the cleanest solution, but it worked for testing in my case.
