### ISSUE TITLE
Solrmarc + Solr 4 warning

### ISSUE THREAD

**Issue by cbeer** [projectblacklight/blacklight#506]
Known issue, doesn't seem to impact functionality, but looks bad.

$ rake solr:marc:index  MARC_FILE=../../test_support/data/test_data.utf8.mrc 
WARNING: Cucumber-rails required outside of env.rb.  The rest of loading is being defered until env.rb is called.
  To avoid this warning, move 'gem cucumber-rails' under only group :test in your Gemfile
java -Xmx512m  -Dsolr.hosturl=http://127.0.0.1:8983/solr  -jar /Volumes/TempStorage/Projects/blacklight/lib/SolrMarc.jar /Volumes/TempStorage/Projects/blacklight/tmp/test_app/config/SolrMarc/config.properties ../../test_support/data/test_data.utf8.mrc

 INFO [main] (MarcImporter.java:816) - Starting SolrMarc indexing.
 INFO [main] (Utils.java:191) - Opening file: /Volumes/TempStorage/Projects/blacklight/tmp/test_app/config/SolrMarc/config.properties
 INFO [main] (MarcImporter.java:749) -  Connecting to remote Solr server at URL http://127.0.0.1:8983/solr/update
java.io.IOException: Server returned HTTP response code: 500 for URL: http://127.0.0.1:8983/solr/admin/registry.jsp
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1436)
    at java.net.URL.openStream(URL.java:1010)
    at org.solrmarc.solr.SolrCoreLoader.loadRemoteSolrServer(SolrCoreLoader.java:351)
    at org.solrmarc.marc.MarcImporter.getSolrServerProxy(MarcImporter.java:750)
    at org.solrmarc.marc.MarcImporter.loadLocalProperties(MarcImporter.java:193)
    at org.solrmarc.marc.MarcHandler.loadProperties(MarcHandler.java:172)
    at org.solrmarc.marc.MarcHandler.init(MarcHandler.java:118)
    at org.solrmarc.marc.MarcImporter.main(MarcImporter.java:822)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.simontuffs.onejar.Boot.run(Boot.java:334)
    at com.simontuffs.onejar.Boot.main(Boot.java:170)

**Comment by arafalov** [comment]
The registry.jsp exception is still there in 5.9.0 and happens during the Quickstart process.
