### ISSUE TITLE
Use secrets.yml in rails 4.1

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/blacklight#939]
In rails 4.1 not setting the secret key gives this error:

```
/Users/justin/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/blacklight-5.4.0/lib/blacklight/rails/routes.rb:20:in `raise_no_blacklight_secret_key': Blacklight.secret_key was not set. Please add the following to an initializer: (RuntimeError)

Blacklight.secret_key = '679d736b2d27d018a28348a2f08286bb05f9827fe977a82add180b7dc18c229871b289a7ee747ef8c71945556fc30cafd7a734575559d634821441dee024cecd'

Please ensure you restarted your application after installing Blacklight or setting the key.
    from /Users/justin/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/blacklight-5.4.0/lib/blacklight/rails/routes.rb:10:in `blacklight_for'
    from /Users/justin/workspace/tufts-image-library/config/routes.rb:4:in `block in <top (required)>'
    from /Users/justin/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/actionpack-4.1.2/lib/action_dispatch/routing/route_set.rb:337:in `instance_exec'
```

Despite the fact that the generated initializer says: `In Rails 4, Blacklight will use the application's secret key base instead.`

**Comment by mark-dce** [comment]
yup - except a google search on the error message leads you here at least ;)
